defmodule Rez.Cookbook.CookbookFile do
  @moduledoc """
  `Rez.Cookbook.CookbookFile` manages the auto-generated `lib/cookbook.rez` file
  that includes all installed cookbook modules.
  """

  alias Rez.Cookbook.Config

  @header """
  %% Auto-generated by rez cookbook. Do not edit manually.
  %% Include this file in your game source with: %(../lib/cookbook.rez)
  """

  def regenerate(game_root) do
    cookbook_path = Config.cookbook_lib_path(game_root)

    includes =
      Path.wildcard(Path.join(cookbook_path, "**/*.rez"))
      |> Enum.sort()
      |> Enum.map(fn abs_path ->
        rel = Path.relative_to(abs_path, game_root)
        "%(../#{rel})"
      end)
      |> Enum.join("\n")

    content = if includes == "", do: @header, else: @header <> "\n" <> includes <> "\n"
    File.write!(Config.cookbook_rez_path(game_root), content)
  end
end
