defmodule Rez.Cookbook.CookbookFile do
  @moduledoc """
  `Rez.Cookbook.CookbookFile` manages the auto-generated `lib/cookbook.rez` file
  that includes all installed cookbook modules.
  """

  alias Rez.Cookbook.{Config, Manifest}

  @header """
  %% Auto-generated by rez cookbook. Do not edit manually.
  %% Include this file in your game source with: %(../lib/cookbook.rez)
  """

  def regenerate(game_root) do
    case Manifest.read(game_root) do
      {:ok, entries} -> write(game_root, entries)
      {:error, _} -> :ok
    end
  end

  defp write(game_root, entries) do
    includes =
      entries
      |> Enum.filter(fn {_path, _ref, type} -> type in ["lib", "both"] end)
      |> Enum.map(fn {module_path, _ref, _type} ->
        "%(../lib/#{Config.dir_name()}/#{module_path}.rez)"
      end)
      |> Enum.join("\n")

    content = if includes == "", do: @header, else: @header <> "\n" <> includes <> "\n"

    File.write!(Config.cookbook_rez_path(game_root), content)
  end
end
