= Behaviour Tasks Catalog
:toc:
:toc-title: Built-in behaviours

== SEQUENCE

The `SEQUENCE` task takes two or more children and when executed will execute its children in turn. If any child fails then `SEQUENCE` will stop at that point and fail. If all the children suceeed then `SEQUENCE` will succeed.

== SELECT

The `SELECT` task takes two or more children and when executed will execute its hildren in turn. If a child succeeds then `SELECT` will immediately stop executing and succeed. If all the children fail then `SELECT` will fail.

== SELECT_P

The `SELECT_P` task is a variant on `SELECT`. It takes a probability option `p` and before executing any child will test `p`. If the test succeeds it will execute that child and task similar to `SELECT`. If no children get executed or all the children fail then `SELECT_P` will fail.

=== Options

[cols="1,1,1"]
|===
|`p`
|1-100
|probability of any given child getting executed
|===

== LOOP

The `LOOP` task takes one child and executes it a number of times specified by the option `count`. If the child should fail then `LOOP` fails. If the child succeeds each time then `LOOP` succeeds.

=== Options

[cols="1,1,1"]
|===
|`count`
|positive integer
|number of times to execute the child
|===

== LOOP_UNTIL

The `LOOP_UNTIL` task takes one child and attempts to execute it a number of times specified by the option `attempts`. If the child succeeds then `LOOP_UNTIL` succeeds. If the child never succeeds then `LOOP_UNTIL` fails.

=== Options

[cols="1,1,1"]
|===
|`attempts`
|positive integer
|number of attempts to execute the child
|===

== MAYBE

The `MAYBE` task takes one child and based on a probability option `p` decides whether to attempt to execute it or not. If the `p` test succeeds the child gets executed and `MAYBE` will succeed or fail based on whether the child succeeds or fails. If the `p` test fails then `MAYBE` fails.

=== Options

[cols="1,1,1"]
|===
|`p`
|1-100
|probability of the child being executed
|===

== EITHER

The `EITHER` task takes two children and based on the probability option `p` decides whether to execute the first or the second child. If the `p` test succeeds then the first child is executed, otherwise the second child is executed. `EITHER` succeeds or fails based on whether the child it executes succeeds or fails.

=== Options

[cols="1,1,1"]
|===
|`p`
|1-100
|probability of the first child getting executed
|===

== RANDOM_CHOICE

The `RANDOM_CHOICE` task takes at least two children and executes one child at
random. If the child succeeds then `RANDOM_CHOICE` succeeds, otherwise it
fails.

== RANDOM_EACH

The `RANDOM_EACH` task takes at least two children and executes one child at
random. `RANDOM_EACH` succeeds or fails based on the selected child succeeding
or failing.

Once a child has been executed it is not eligible to be selected again until
all the other children of `RANDOM_EACH` have, likewise, been executed. When all
the children have been executed `RANDOM_EACH` will begin again with a new
random order of children.

== INVERT

The `INVERT` task takes one child and executes it. If the child succeeds then
`INVERT` fails, likewise if the child fails then `INVERT` will succeed.

== ALWAYS

The `ALWAYS` task takes one child and executes it. It ignores whether the child
succeeds or fails and always suceeds itself.

== NEVER

The `NEVER` task takes one child and executes it. It ignores whether the child
succeeds or fails, always failing itself. It's a shorthand for
`[INVERT [ALWAYS ...]]`.

== SUCCEED

The `SUCEED` task takes no chilren and when executed it always succeeds.

== FAIL

The `FAIL` task takes no children and when executed it always fails.
